language: d
sudo: required
packages:
  - pkg-config
d:
 - gdc
 - ldc
 - ldc-beta
 - dmd-nightly
 - dmd-beta
 - dmd

branches:
  only:
    - master
env:
 - ARCH="x86_64"
matrix:
  include:
    - {os: linux, d: ldc-beta, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
    - {os: linux, d: ldc, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
    - {os: linux, d: dmd-beta, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
    - {os: linux, d: dmd, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
  allow_failures:
    - {d: dmd-nightly}
    - {d: ldc-beta}
    - {d: gdc}

script:
 - dub test --arch "$ARCH"
